### ISSUE TITLE
"invalid_grant"

### ISSUE THREAD

**Issue by c27cochran** [docusign/eg-01-node-jwt#1]
I downloaded your example code and it appears to be broken.

After following all of the steps, I receive:

```Send an envelope with three documents. This operation takes about 15 seconds...
checkToken: Starting up--need a token

API problem: Status code 400, message body:
{
    "error": "invalid_grant"
}
```

**Comment by c27cochran** [comment]
Never mind. I was using the client secret for the client ID.

You guys need to be way more clear in your docs. 

For anyone that's having this same issue, there is no such thing as a "client ID"...it's actually called an "integrator key".

**Comment by LarryKlugerDS** [comment]
Hi @c27cochran,

I'm sorry that the information was clearer. I will recheck the client id documentation within the example. `client id` is the OAuth term. `Integrator Key` is the DocuSign equivalent. We are moving towards using client id in many places since it is the standard OAuth term.

Thank you for developing with DocuSign.

Regards,
Larry
