### ISSUE TITLE
consent_required because response_type=code

### ISSUE THREAD

**Issue by duyan90** [docusign/eg-01-node-jwt#9]
Hello guys;
I try to use your sample to get access token but got the error because the link always generate 
response_type=code not token like the official document.
https://developers.docusign.com/esign-rest-api/guides/authentication/oauth2-implicit
If i change the scopes in file dsJwtAuth.js from signature  to impersonation i also get the token but get the error 401 because the scope is not correct.

Currently, i manually use other lib to call API to get the access token. 
Please help me to resolve this bug.

**Comment by LarryKlugerDS** [comment]
I think there is a miscommunication here:

The common flow of using this example is:

1. Configure the example and set up the client_id (integration key) on the DocuSign platform.
1. Run the example. You should get the consent required error, along with the instructions on how to individually grant consent (by using the url which eventually returns a authorization code).

   You do **not** use the authorization code for anything. Rather, you are just trying to grant consent to your client id.
1. Now re-run this example. This time, the example should complete with no errors. The example obtains an access token directly from DocuSign and then uses it. No human interaction is needed since the JWT OAuth flow is used.

**Comment by LarryKlugerDS** [comment]
Please re-open / comment if you have further questions. This type of question can also be asked on StackOverflow by using the `docusignapi` tag.
